sudo: required

language: php

services:
  - docker

env:
  global:
    - REPO=barvoj/fpm

before_install:
  - sudo /etc/init.d/mysql stop

install:
  # Download all images
  - docker pull selenium/standalone-firefox-debug:2.53.0
  - docker pull codeception/codeception
  - docker pull bartos/composer
  - docker pull node

before_script:
  #  - chmod -R 777 log temp
  - touch ./app/config.environment.local.php
  - echo "<?php define('ENVIRONMENT', ENV_LOCAL);" >> ./app/config.environment.local.php

  # Generate private key
  - openssl aes-256-cbc -K $encrypted_5b9f08960f5d_key -iv $encrypted_5b9f08960f5d_iv -in id_rsa.enc -out id_rsa -d

  # Use as SSH key
  - chmod 600 id_rsa
  - mv id_rsa ~/.ssh/id_rsa

  # Copy config.local.neon
  - scp -P 11172 -o 'StrictHostKeyChecking no' app@alpha-node-2.rosti.cz:/srv/app_configs/config.local.test.neon ./app/config/config.local.neon

  # Install dependecies
  - docker run --rm --volume `pwd`:/project -w /project bartos/composer install
  - docker run --rm --volume `pwd`:/project -w /project node npm install
  - docker run --rm --volume `pwd`:/project -w /project node node_modules/webpack/bin/webpack.js

  - docker build -f Dockerfile -t $REPO .

  # Run containers
  - docker-compose up -d

  # Wait for containers to start
  - sleep 30

  # Run migrations
  - docker exec -u www-data:www-data vb_fpm bash -c "php /project/www/index.php migrations:continue"

  # Run firefox
  - docker run -d -p 4444:4444 -p 5900:5900 --name firefox --link vb_nginx:nginx --net vojtechbartoscom_default selenium/standalone-firefox-debug:2.53.0

  # Wait for firefox to start
  - sleep 30

script:
  # Run Codeception
  - docker run --rm --volume `pwd`:/project --link firefox --net vojtechbartoscom_default codeception/codeception run accept

after_script:
  # Stop and remove containers
  - docker stop firefox
  - docker rm firefox
  - docker-compose down

  # Upload logs
  - mkdir ./logs
  - docker cp vb_data:/project/log ./logs/log
  - docker cp vb_data:/project/tests/CodeCeption/_output ./logs/_output
  - zip -r ./log.zip ./logs
  - scp -P 11172 -o 'StrictHostKeyChecking no' ./log.zip app@alpha-node-2.rosti.cz:/srv/builds/$TRAVIS_BUILD_NUMBER.zip
  - rm -rf ./logs log.zip

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    repo: Barvoj/vojtechbartos.com