language: php

sudo: false

php:
  - 7.0

before_install:
  # Update composer
  - travis_retry composer self-update

install:
  # Install dependecies
  - travis_retry composer install --no-interaction --prefer-source -o

script:
  # Run Nette Tester
  - vendor/bin/tester tests -s -p php