version: '2'
services:
  data:
#    container_name: "data"
    build: ./
    volumes:
      - .:/project
    command: "true"
  nginx:
    image: bartos/nginx:nette
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - data
    links:
      - php
  php:
    image: bartos/php
    ports:
      - "9000:9000"
    volumes_from:
      - data
    links:
      - mysql
#      - blackfire
  mysql:
    image: bartos/mysql
    ports:
      - "3306:3306"
    volumes_from:
      - data
    environment:
      - MYSQL_ROOT_PASSWORD=root
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
  redis:
    image: redis
#  composer:
#    image: bartos/composer
#    command: install
#    volumes_from:
#      - data
#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      - BLACKFIRE_SERVER_ID=9fe25e0d-19b3-405b-832f-846f8d7cae4b
#      - BLACKFIRE_SERVER_TOKEN=b08cf68aaa559dd542004ae8261e4f1b74c952a56837f914021cbb9a5de42134
#  npm:
#    image: node
##    command: install
#    volumes_from:
#      - data
#    working_dir: /project
#    entrypoint: ['npm', '--no-bin-link']
#  webpack:
#    image: node
#    command: install
#    volumes_from:
#      - data
#    working_dir: /project
#    entrypoint: ['node_modules/webpack/bin/webpack.js']
#  codeception:
#    image: codeception/codeception
#    depends_on:
#      - firefox
#      - nginx
#    volumes_from:
#      - data
#    volumes:
#      - ./src:/src
#      - ./tests:/tests
#      - ./codeception.yml:/codeception.yml
#      - .:/project
#  firefox:
#    image: selenium/standalone-firefox-debug:2.53.0
#    ports:
#      - '4444'
#      - '5900'