data:
  build: ./
  volumes:
  - ".:/var/www/project"
  - "db:/docker-entrypoint-initdb.d"
nginx:
  image: bartos/nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - data
  links:
    - php
php:
  image: bartos/php
  ports:
    - "9000:9000"
  volumes_from:
    - data
  links:
    - mysql
mysql:
  image: bartos/mysql
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    - MYSQL_ROOT_PASSWORD=root
#utils:
#  image: bartos/utils
#  volumes_from:
#    - data
composer:
  restart: 'no'
  image: composer/composer:php7
  command: install
  volumes:
    - .:/app