data:
  build: ./
  volumes:
  - ".:/var/www/project"
nginx:
  image: bartos/nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - data
  links:
    - php
php:
  image: bartos/php
  ports:
    - "9000:9000"
  volumes_from:
    - data
utils:
  image: bartos/utils
  volumes_from:
    - data