version: '2'
services:
  nginx:
    container_name: "vb_nginx"
    image: bartos/nginx:nette
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - php
    links:
      - php
  php:
    container_name: "vb_fpm"
    image: barvoj/fpm
    ports:
      - "9000:9000"
    links:
      - mysql
#      - blackfire
  mysql:
    container_name: "vb_mysql"
    image: barvoj/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  rabbit:
    container_name: "vb_rabbit"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "15672:15672"
  redis:
    container_name: "vb_redis"
    image: redis
    ports:
      - "6379:6379"
#  composer:
#    image: bartos/composer
#    command: install
#    volumes_from:
#      - data
#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      - BLACKFIRE_SERVER_ID=9fe25e0d-19b3-405b-832f-846f8d7cae4b
#      - BLACKFIRE_SERVER_TOKEN=b08cf68aaa559dd542004ae8261e4f1b74c952a56837f914021cbb9a5de42134
#  npm:
#    image: node
##    command: install
#    volumes_from:
#      - data
#    working_dir: /project
#    entrypoint: ['npm', '--no-bin-link']
#  webpack:
#    image: node
#    command: install
#    volumes_from:
#      - data
#    working_dir: /project
#    entrypoint: ['node_modules/webpack/bin/webpack.js']