apiVersion: v1
kind: Service
metadata:
  name: fpm
  labels:
    app: vojtechbartos
spec:
  type: NodePort
  ports:
  - port: 9000
  selector:
    app: vojtechbartos
    service: fpm
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fpm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vojtechbartos
        service: fpm
        tier: backend
    spec:
      containers:
      - name: fpm
        image: barvoj/fpm
        imagePullPolicy: Always
        ports:
        - containerPort: 9000