apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: vojtechbartos
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: vojtechbartos
    service: nginx
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vojtechbartos
        service: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: bartos/nginx:nette
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 443