apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    app: vojtechbartos
spec:
  type: NodePort
  ports:
  - name: node
    port: 5672
  - name: management
    port: 15672
  selector:
    app: vojtechbartos
    service: rabbitmq
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vojtechbartos
        service: rabbitmq
        tier: backend
    spec:
      containers:
      - name: vb-rabbit
        image: rabbitmq:3-management
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: admin
