apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: vojtechbartos
spec:
  type: NodePort
  ports:
  - port: 6379
  selector:
    app: vojtechbartos
    service: redis
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vojtechbartos
        service: redis
        tier: backend
    spec:
      containers:
      - name: vb-redis
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
